# Generated by Django 5.2.6 on 2025-09-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='اسم الشركة')),
                ('offer_title', models.CharField(max_length=200, verbose_name='عنوان العرض')),
                ('offer_details', models.TextField(verbose_name='تفاصيل العرض')),
                ('promo_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='البروموكود')),
                ('logo', models.ImageField(upload_to='logos/', verbose_name='شعار الشركة')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('is_active', models.BooleanField(default=True, verbose_name='هل العرض فعال؟')),
            ],
        ),
    ]
