# Generated by Django 5.2.6 on 2025-09-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='اسم الطالب')),
                ('student_details', models.CharField(max_length=100, verbose_name='تفاصيل الطالب (مثال: سنة 3)')),
                ('quote', models.TextField(verbose_name='نص التقييم')),
                ('is_featured', models.BooleanField(default=False, verbose_name='هل يظهر في الصفحة الرئيسية؟')),
            ],
        ),
    ]
