# Generated by Django 5.2.6 on 2025-09-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='academic_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='الفرقة الدراسية'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='college',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الكلية'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'ولد'), ('female', 'بنت')], max_length=10, null=True, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id_photo',
            field=models.FileField(blank=True, null=True, upload_to='id_photos/', verbose_name='صورة إثبات الهوية'),
        ),
    ]
