# Generated by Django 5.2.6 on 2025-09-21 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المقرر')),
                ('course_code', models.CharField(max_length=20, unique=True, verbose_name='كود المقرر')),
                ('academic_year', models.IntegerField(verbose_name='الفرقة الدراسية')),
                ('description', models.TextField(blank=True, verbose_name='وصف المقرر')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المادة')),
                ('material_type', models.CharField(choices=[('pdf', 'ملف PDF'), ('video', 'فيديو'), ('summary', 'ملخص'), ('exam', 'امتحان سابق')], max_length=10, verbose_name='نوع المادة')),
                ('file', models.FileField(upload_to='course_materials/', verbose_name='الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course', verbose_name='المقرر التابع له')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='رافع المادة')),
            ],
        ),
    ]
