# Generated by Django 5.2.6 on 2025-09-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_enrolled_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_demo',
            field=models.BooleanField(default=False, verbose_name='هل هو مقرر تجريبي للضيوف؟'),
        ),
    ]
