# Generated by Django 5.2.6 on 2025-09-21 02:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الفرصة')),
                ('company_name', models.CharField(max_length=100, verbose_name='اسم الشركة/الجهة')),
                ('location', models.CharField(max_length=100, verbose_name='الموقع')),
                ('description', models.TextField(verbose_name='الوصف والتفاصيل')),
                ('opportunity_type', models.CharField(choices=[('internship', 'تدريب صيفي'), ('full-time', 'وظيفة بدوام كامل'), ('workshop', 'ورشة عمل'), ('competition', 'مسابقة')], max_length=20, verbose_name='نوع الفرصة')),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ النشر')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء التقديم')),
                ('link_to_apply', models.URLField(verbose_name='رابط التقديم')),
            ],
        ),
    ]
